---
- name: Install and configure Nginx
  hosts: nginx
  become: true
  vars:
    nginx_listen_port: 8080
  tasks:
   - name: Install EPEL Repo package from standard repo
     yum:
      name: epel-release
      state: present

   - name: NGINX | Install NGINX package from EPEL Repo
     yum:
      name: nginx
      state: latest
     notify:
      - restart nginx
     tags:
      - nginx-package
      - packages
      - nginx-install 

   - name: NGINX | Create Nginx config from template
     template:
      src: templates/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
     notify:
      - reload nginx
     tags:
      - nginx-configuration

  handlers:
   - name: restart nginx
     systemd:
       name: nginx
       state: restarted
       enabled: yes
    
   - name: reload nginx
     systemd:
       name: nginx
       state: reloaded
