# -*- mode: ruby -*-
# vim: set ft=ruby :


Vagrant.configure("2") do |config|

    config.vm.define "nginx" do |nginx|

	config.vm.box="centos/7"        
        nginx.vm.hostname = "nginx"
	nginx.vm.network "forwarded_port", guest: 8080, host: 8080
	nginx.vm.network "private_network", ip: "192.168.11.150", netmask: "255.255.255.0", virtualbox__intnet: "net9"

        
	nginx.vm.provider "virtualbox" do |vb|
         vb.memory="512"
        end

        nginx.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
	  sudo sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
          sudo systemctl restart sshd
	SHELL
    end  


    config.vm.define "host2" do |host2|

        config.vm.box="centos/7"
        host2.vm.hostname = "host2"
        host2.vm.network "private_network", ip: "192.168.11.151", netmask: "255.255.255.0", virtualbox__intnet: "net9"


        host2.vm.provider "virtualbox" do |vb|
         vb.memory="256"
        end

        host2.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
    end


end
