# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :Host1 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '10.0.0.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "net"},
                ]
  },
  :Host2 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '10.0.0.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "net"},
                ]
  },
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.hostname = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
		  
		box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "512"]
        end
        

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
          sudo -i
yum install -y redhat-lsb-core && yum install -y wget && yum install -y rpmdevtools && yum install -y rpm-build && yum install -y createrepo && yum install -y yum-utils && yum install -y gcc
wget -P /root/ https://nginx.org/packages/centos/7/SRPMS/nginx-1.14.1-1.el7_4.ngx.src.rpm
wget -P /root/ https://www.openssl.org/source/openssl-1.1.1d.tar.gz
wget -P /root/ http://mirror.centos.org/centos/7/os/x86_64/Packages/tftp-5.2-22.el7.x86_64.rpm
rpm -i /root/nginx-1.14.1-1.el7_4.ngx.src.rpm
mkdir /root/openssl-1.1.1d
tar -xvf /root/openssl-1.1.1d.tar.gz -C /root/
yum-builddep -y /root/rpmbuild/SPECS/nginx.spec
sed -i 's+with-debug+with-openssl=/root/openssl-1.1.1d+g' /root/rpmbuild/SPECS/nginx.spec
rpmbuild -bb /root/rpmbuild/SPECS/nginx.spec
yum localinstall -y /root/rpmbuild/RPMS/x86_64/nginx-1.14.1-1.el7_4.ngx.x86_64.rpm
mkdir /usr/share/nginx/html/repo
cp /root/rpmbuild/RPMS/x86_64/nginx-1.14.1-1.el7_4.ngx.x86_64.rpm /usr/share/nginx/html/repo/
cp /root/tftp-5.2-22.el7.x86_64.rpm /usr/share/nginx/html/repo/
createrepo /usr/share/nginx/html/repo/
sed -i '10 a autoindex on;' /etc/nginx/conf.d/default.conf
systemctl restart nginx
	SHELL
        

      end

  end
  
  
end
end
