# -*- mode: ruby -*-
# vim: set ft=ruby :


Vagrant.configure("2") do |config|


    config.vm.define "inetRouter" do |inetRouter|
        config.vm.box="centos/7"
        inetRouter.vm.hostname="inetRouter"
        inetRouter.vm.network "private_network", ip: "192.168.255.1", netmask: "255.255.255.252", virtualbox__intnet: "router-net"
	inetRouter.vm.provision "shell", inline: <<-SHELL
	  systemctl restart network
	 # yum -y install iptables-services
	  systemctl restart network
	  ip route add 192.168.0.0/16 via 192.168.255.2 dev eth1
          iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
	  iptables -N TRAFFIC
	  iptables -A INPUT -s 10.0.0.0/8 -j ACCEPT
	  iptables -P INPUT DROP
	  iptables -A INPUT -j TRAFFIC
	  iptables -A TRAFFIC -p icmp --icmp-type any -j ACCEPT
	  iptables -A TRAFFIC -m state --state ESTABLISHED,RELATED -j ACCEPT
	  iptables -A TRAFFIC -m state --state NEW -p tcp --dport 22 -m recent --rcheck --seconds 30 --name SSH0 -j ACCEPT
	  iptables -A TRAFFIC -m state --state NEW -p tcp -m recent --name SSH0 --remove -j REJECT
	  iptables -A TRAFFIC -m state --state NEW -p tcp -m recent --name SSH0 --remove -j REJECT
	  iptables -A TRAFFIC -m state --state NEW -p tcp --dport 6666 -m recent --name SSH0 --set -j REJECT
	  iptables -A TRAFFIC -j REJECT
          sysctl net.ipv4.conf.all.forwarding=1
	SHELL
    end


    config.vm.define "inet2Router" do |inet2Router|
        config.vm.box="centos/7"
        inet2Router.vm.hostname="inet2Router"
        inet2Router.vm.network "private_network", ip: "192.168.255.5", netmask: "255.255.255.252", virtualbox__intnet: "router-net2"
	inet2Router.vm.network "public_network", ip: "192.168.1.122", netmask: "255.255.255.0", bridge: "wlp16s0"
		
	inet2Router.vm.provision "shell", inline: <<-SHELL
	  systemctl restart network
          ip route add 192.168.0.0/16 via 192.168.255.6 dev eth1
	  iptables -A PREROUTING -t nat -i eth2 -p tcp --dport 8080 -j DNAT --to 192.168.0.2:80
          sysctl net.ipv4.conf.all.forwarding=1
	SHELL
    end

    config.vm.define "centralRouter" do |centralRouter|
        config.vm.box="centos/7"
        centralRouter.vm.hostname="centralRouter"
        centralRouter.vm.network "private_network", ip: "192.168.255.2", netmask: "255.255.255.252", virtualbox__intnet: "router-net"
	centralRouter.vm.network "private_network", ip: "192.168.255.6", netmask: "255.255.255.252", virtualbox__intnet: "router-net2"
	centralRouter.vm.network "private_network", ip: "192.168.0.1", netmask: "255.255.255.240", virtualbox__intnet: "server-net"

        centralRouter.vm.provision "shell", inline: <<-SHELL
	  systemctl restart network
          ip route add default via 192.168.255.1 dev eth1
	  ip route add 192.168.1.0/24 via 192.168.255.5 dev eth2
          sysctl net.ipv4.conf.all.forwarding=1
	  yum -y install nmap
        SHELL
    end

    config.vm.define "centralServer" do |centralServer|
        config.vm.box="centos/7"
        centralServer.vm.hostname="centralServer"
        centralServer.vm.network "private_network", ip: "192.168.0.2", netmask: "255.255.255.240", virtualbox__intnet: "server-net"
        centralServer.vm.provision "shell", inline: <<-SHELL
	  systemctl restart network
          ip route add default via 192.168.0.1 dev eth1
          sysctl net.ipv4.conf.all.forwarding=1
	  yum -y install epel-release
	  yum -y install nginx
	  systemctl start nginx
        SHELL
    end


        config.vm.provider "virtualbox" do |vb|
           vb.memory="128"
        end


        config.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL

end 
